/* configuration
 */
let config = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT:  600,
  FRAME_PER_SECOND: 30,
  DEBUG_TEXT_OFFSET: 10,
  BALL_RADIUS: 10,
  BALL_SPEED_X: 5,
  BALL_SPEED_X_FACTOR:  5,
  BALL_SPEED_Y: 10,
  BALL_BOUNCE_BACK:  -1,
  BRICK_SEPARATOR: 0.1,
  MAX_BRICKS_PER_ROW:  20,
  MAX_BRICKS_PER_COLUMN: 20,
  PADDLE_WIDTH: 100,
  PADDLE_HEIGHT: 10,
  PADDLE_SPEED: 50,
  PADDLE_ELEVATION: 10,
  HISTORY_SIZE: 10
}
let constant = {
  SECOND: 1000
}
// computed
{
  config.REFRESH_RATE =  constant.SECOND / config.FRAME_PER_SECOND
  config.PADDLE_POSITION_Y = config.CANVAS_HEIGHT - (config.PADDLE_HEIGHT + config.PADDLE_ELEVATION)
  config.PADDLE_POSITION_BOTTOM_Y = config.CANVAS_HEIGHT - config.PADDLE_ELEVATION
  config.BALL_START_X = config.CANVAS_WIDTH / 2
  config.BALL_START_Y = config.CANVAS_HEIGHT / 2
  config.BRICK_WIDTH = config.CANVAS_WIDTH / config.MAX_BRICKS_PER_ROW
  config.BRICK_HEIGHT = (config.CANVAS_HEIGHT * .5) / config.MAX_BRICKS_PER_COLUMN
  config.BRICK_AMOUNT = config.MAX_BRICKS_PER_ROW * config.MAX_BRICKS_PER_COLUMN
}

// DEBUG
// config.BALL_SPEED_Y = 0
// config.BALL_SPEED_X = -10
// config.BALL_START_X = config.CANVAS_WIDTH - 10
// config.BALL_START_X = 10
// config.BALL_START_Y = 0